repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    sha: v1.4.1
    hooks:
    -   id: validate_manifest
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.19.0
    hooks:
    -   id: yapf
